<?php
	$negativeWords = [
		"121 chat",
		"flu",
		"measles",
		"adult",
		"armed",
		"burglar",
		"cholera",
		"confederate",
		"exploded",
		"exploding ",
		"fucka",
		"fuckas",
		"fuckaz",
		"fuker",
		"gayass",
		"gaybob",
		"gaybois",
		"gayboys",
		"gaydo",
		"gayfuck",
		"gayfuckist",
		"gaylord",
		"gaynightclub",
		"gaytard",
		"measles",
		"nipples",
		"poisoned",
		"pooper",
		"terroristic",
		"torturing",
		"train hits",
		"trapped",
		"zoosex",
		"zoophilia",
		"zombie knives",
		"zipperhead",
		"zipper head",
		"zika virus",
		"Zika",
		"zigabo",
		"zerhacken",
		"zehaf bibeau",
		"zawahiri",
		"Zaventem airport",
		"Zakirjon Almatov",
		"Zakir Naik",
		"ZaharieAhmad",
		"Zaharie Ahmad",
		"yuvutu",
		"Yusuf al Qaradawi",
		"Yunis Al Astal",
		"youporn",
		"younporn",
		"yorkshire ripper",
		"yob",
		"yihadista",
		"yid",
		"yarpie",
		"Yarmouk Martyrs Brigade",
		"xxxrated",
		"xxx",
		"x-rated",
		"xenophobic",
		"xenophobia",
		"Xanax",
		"x rated",
		"wuhan",
		"wrecks",
		"wreckage",
		"wreck",
		"wounds",
		"wounding dozens",
		"wounded",
		"wound",
		"worstmassshooting",
		"worldwar",
		"WorldTradeCenter",
		"World Tamil Movement",
		"world phone hacking",
		"wop",
		"woody",
		"womandies",
		"wog",
		"wobbly pop",
		"willy",
		"willies",
		"wigger",
		"wigga",
		"wield knives",
		"wichse",
		"whores",
		"whoreface",
		"whorebag",
		"whore",
		"whiz",
		"white lives matter",
		"White Defence League",
		"White Aryan Resistance",
		"whistleblower",
		"whigger",
		"whack off",
		"wetT shirt",
		"wetshirt",
		"wetback",
		"wet t-shirt",
		"wet back",
		"weils",
		"wee-wee",
		"weed",
		"wee wee",
		"weapons-grade",
		"weapons",
		"weaponry",
		"weapon",
		"warzone",
		"war-torn",
		"warship",
		"war-ravaged",
		"warplanes",
		"warhead",
		"warfare",
		"warez",
		"wares",
		"warcrimes",
		"war",
		"wanted belgian man",
		"wankers",
		"wanker",
		"wank",
		"wagdi ghoneim",
		"Wada",
		"wad",
		"voyeurweb",
		"voyeurism",
		"voyeur",
		"voyerweb",
		"voyer web",
		"voodoo",
		"Vojislav Šešelj",
		"vojislav seselj",
		"vjayjay",
		"vivitrol",
		"virgin",
		"violent",
		"violencia",
		"violence",
		"violating",
		"violate",
		"violaciones",
		"violacion",
		"vile posts",
		"Vigrid",
		"victims",
		"victimized",
		"victimised",
		"victimes",
		"victim",
		"vicodin",
		"vibrators",
		"vibrator",
		"viagra",
		"Vester Flanagan",
		"vessel started sinking",
		"vehicles smashing",
		"vehicleaccident",
		"vehicle veered off",
		"vehicle collided",
		"vehicle ablaze",
		"vatnyk",
		"vatnik",
		"vaping",
		"vape",
		"vanishedjet",
		"vanished jet",
		"Vanguards of Conquest",
		"vandalism",
		"van plough",
		"vaginas",
		"vagina",
		"vag",
		"uv radiation",
		"utorrent",
		"Usman Ghazi",
		"urinieren",
		"urinal",
		"urin",
		"urea injection",
		"uranium-enrichment",
		"uranium enrichment",
		"upskirts",
		"upskirting",
		"upskirt",
		"up yours",
		"up the skirt",
		"up skirt",
		"unzensiert",
		"unlocking iPhone",
		"unlawful",
		"Universal White Brotherhood",
		"United SelfDefense Forces",
		"United Patriots Front",
		"United Liberation Front",
		"unite the right",
		"Union Movement",
		"Unheil",
		"under the rubble",
		"unconscious",
		"unclefucker",
		"un peacekeepers",
		"umbringen",
		"Umbilical Cord",
		"Ulster Volunteer Force",
		"Ulster Defence Association",
		"Ugursuzluk",
		"uav",
		"twink",
		"twatwaffle",
		"twats",
		"twatlips",
		"twat",
		"turd",
		"tueur",
		"tube8",
		"Tsagaan Khas",
		"truck that plowed",
		"truck plows into",
		"truck ploughs",
		"truck ploughed into",
		"truck plough",
		"trippy",
		"Trevor Smith",
		"traumatising",
		"traumatised",
		"trauma",
		"tram overturns",
		"tram derail",
		"trajedi",
		"traincrash",
		"trailer trash",
		"tragedy",
		"trafficking",
		"trafficcollision",
		"trafficaccident",
		"tracer rounds",
		"toy freak style",
		"toxins",
		"toxin",
		"toxic",
		"tower blaze",
		"towelhead",
		"towel head",
		"tosspot",
		"tosser",
		"tortures",
		"torturer",
		"tortured",
		"torture",
		"topless",
		"tohir yoldosh",
		"todotorrents",
		"Todesopfer",
		"Todd Bentley",
		"tobacco",
		"tittyfuck",
		"titties",
		"tittie",
		"titten",
		"tits",
		"titfuck",
		"titanime",
		"tit",
		"Timo Glock",
		"tiersex",
		"thundercunt",
		"thug",
		"throws a punch",
		"thrown overboard",
		"throwing bottles",
		"threeway woman",
		"threesomes",
		"threesome",
		"three-car smash",
		"three some",
		"threats against westerners",
		"threat to westerners",
		"thong",
		"Thomas Mapfumo",
		"Thomas Hite",
		"thieving",
		"thieves",
		"thieve",
		"thicklips",
		"theft",
		"theatre collapse",
		"theater collapse",
		"The Saved Sect",
		"the peoples temple",
		"the NRA",
		"The National Front",
		"The British Movement",
		"Thaksin Shinawatra",
		"thaad",
		"TGN267",
		"Texasexplosion",
		"Tevhid Selam",
		"testing on animals",
		"testing laboratory",
		"testicle",
		"test on animals",
		"Terry Jones",
		"Terrorwelle",
		"terror-watch",
		"Terrorwarnstufe",
		"Terrorverdacht",
		"terrorsuspect",
		"terrorshooting",
		"Terrormiliz",
		"terrorists",
		"terroristic threats",
		"terroristes",
		"Terroristen",
		"terroriste",
		"terroristattack",
		"terrorist",
		"Terrorismus",
		"terrorismo",
		"terrorisme",
		"terrorism",
		"Terrorgruppe",
		"terrorcell",
		"terrorblasts",
		"terror",
		"Terrance Quaites",
		"teror orgutu",
		"Temazepam",
		"teletubbies",
		"teensex",
		"tear gas",
		"tea bagging",
		"tax evasion",
		"Tashfeen Malik",
		"taser",
		"targeted westerners",
		"tard",
		"tar baby",
		"Tanzim",
		"Tamil National Retrieval",
		"Tamil Nadu Liberation",
		"TamerlanTsarnaev",
		"tamerlan tsarnaev",
		"talihsizlik",
		"Taksim Square",
		"takfiri",
		"Takfir wal Hijra",
		"take his own life",
		"take her own life",
		"take a dump",
		"tailstrike",
		"taig",
		"tahlihsizliker",
		"tacohead",
		"Syed Rizwan Farook",
		"Syed Farook",
		"sxxe",
		"sxe",
		"swingers",
		"swingerclub",
		"swinger",
		"swine flu",
		"swindle",
		"swear word",
		"swastika",
		"suspicious package",
		"suspicious device",
		"suspects",
		"suspect device",
		"suspect",
		"Surrogate Mother",
		"Supreme Military Majlis",
		"supremacy",
		"Supremacists",
		"supremacist",
		"sumisa",
		"Sultanahmette Saldiri",
		"sultanahmette patlama haberi",
		"sultanahmet patlama",
		"sultanahmet meydaninda patlama",
		"Sultanahmet Meydani",
		"Sultanahmet cami",
		"Sultan Ahmet Platz",
		"sukyo mahikari",
		"suizid",
		"suicides",
		"suicidenote",
		"suicide",
		"suicidal",
		"suffers stroke",
		"suffered a stroke",
		"suffered",
		"sucking balls",
		"sucker",
		"suck off",
		"suck me",
		"suck a fatty",
		"subtorrent",
		"submarine hits ship",
		"submachine",
		"Students Islamic Movement",
		"struck by debris",
		"Stroker",
		"striptease",
		"stripshow",
		"Stripper",
		"stripped",
		"stripgirl",
		"stripclub",
		"stricken aircraft",
		"strapon",
		"strap on",
		"strangle",
		"stoneman douglas",
		"stimulants",
		"stimulant",
		"stillborn",
		"stillbirth",
		"still birth",
		"stiffy",
		"Stichting Al Aqsa",
		"steroids",
		"steroid",
		"stealth fighter",
		"stealing",
		"steal",
		"state of emergency",
		"stabbing",
		"stabbed",
		"stab",
		"squirt n spurt",
		"squinty",
		"spy planes",
		"spread hatred",
		"spot trolls",
		"Sports therapy",
		"spooge",
		"spoof calling",
		"spoof call free",
		"spoof call",
		"spong bob",
		"splooge",
		"spik",
		"spigotty",
		"spig",
		"spick",
		"spice tv",
		"spice movies",
		"spic",
		"sperma",
		"sperm whale",
		"sperm donor",
		"speedball",
		"special forces",
		"spearchucker",
		"spear chunker",
		"spaz",
		"spanking",
		"spank",
		"Soykirim",
		"Sotloff",
		"Son Dakika Haberler",
		"Son Dakika Haberi",
		"somalianpirates",
		"somalian pirates",
		"Somali al-Shabab",
		"somali al shabab",
		"Solidarity with Palestine",
		"softcore",
		"sodomy",
		"sodomitical",
		"sodomitic",
		"sodomites",
		"sodomite",
		"sodomists",
		"sodomist",
		"sodomie",
		"Society Revival Islamic",
		"Socialist Reich Party",
		"snipers",
		"sniper",
		"sneefen",
		"snatch",
		"smut",
		"smuggling",
		"smoldering remains",
		"smoking",
		"smokey bear",
		"Smoker",
		"smoke in the cockpit",
		"smoke in the cabin",
		"smoke coming from",
		"smeg",
		"smashed up",
		"smashed into the",
		"smashed into pedestrians",
		"smackhead",
		"slut-shamed",
		"sluts",
		"slutbag",
		"slut",
		"slur",
		"sleeper-cells",
		"sleeper cells",
		"slaying",
		"Slavery",
		"Slave",
		"slaughtering",
		"slaughtered",
		"slaughter",
		"slapper",
		"slain",
		"Slags",
		"skullfuck",
		"skinheads",
		"skhije",
		"sket",
		"skank",
		"sitorayusufiy",
		"sin tangas",
		"sin tanga",
		"sin bragas",
		"Sikh Youth Federation",
		"siege",
		"sidearm",
		"Sick",
		"Siccatune Alcock",
		"sicarios",
		"shrapnel",
		"shots",
		"shotgunning",
		"shotgun",
		"shot",
		"short-circuit and ignite",
		"shop lifting",
		"Shop lifters",
		"shop lifter",
		"shop lift",
		"shootings",
		"shooting",
		"shooters",
		"shooter",
		"shiznit",
		"shiz",
		"shitty",
		"shittings",
		"shitting",
		"shittiest",
		"shitters",
		"shitter",
		"shitted",
		"shitstorm",
		"shitstain",
		"shitspitter",
		"shits",
		"shitlist",
		"shitings",
		"shiting",
		"shithouse",
		"shithole",
		"shithead",
		"shitfit",
		"shitfaced",
		"shitface",
		"shited",
		"shitdick",
		"shitcunt",
		"shitbreath",
		"shitbrains",
		"shitbagger",
		"shitbag",
		"shitass",
		"shit",
		"shipwreck",
		"ship started sinking",
		"Ship sinks",
		"ship sank",
		"Sheikh Mukhtar Robow",
		"Sheikh Ahmed Yassin",
		"sheathcell",
		"shark bites",
		"shark bit",
		"shagging",
		"shagger",
		"Shabaab",
		"sexywomen",
		"sexysat",
		"sexy",
		"sexxx",
		"sexvideos",
		"sexvideo",
		"sexually",
		"sexualassault",
		"sexual",
		"sextoys",
		"sexszene",
		"sexsy",
		"sexsites",
		"sexshops",
		"sexshop",
		"sexs",
		"sexpussi",
		"sexo",
		"sexline",
		"Sexist",
		"sexism",
		"SexiestWomen",
		"sexi",
		"sexhotline",
		"sexfantasie",
		"sexdvd",
		"sexdating",
		"sexcrimes",
		"sexclub",
		"sexchat",
		"sexbar",
		"sexabuse",
		"sex",
		"Sewol",
		"severed head",
		"severe burns",
		"set him alight",
		"set her alight",
		"serialz",
		"serials",
		"Serge Aurier",
		"separatist offensive",
		"send prank calls",
		"semi-automatic",
		"selbstmord tabletten",
		"Selbstmord Attentat",
		"selbstmord",
		"seized by alligator",
		"security threat",
		"security forces",
		"secondhand smoke",
		"second hand smoke",
		"Second Amendment",
		"search efforts",
		"search crew",
		"search and rescue",
		"search and recovery",
		"sea rescue",
		"scrote",
		"screwing",
		"screwed",
		"scrambles Typhoons",
		"Scottish separatists",
		"scat",
		"scandals",
		"scandalous",
		"scandal",
		"save animals",
		"savage terror",
		"sausage jockey",
		"sars",
		"sarin",
		"sara zelenak",
		"Saor Éire",
		"saor eire",
		"sandra bollocks",
		"sandnigger",
		"Samy Amimour",
		"Samir Kuntar",
		"samen",
		"samantha lewthwaite",
		"salmonella",
		"salman abedi",
		"Salil al sawarim",
		"Saleel Sawarim",
		"Salah Abdeslam",
		"Saif al Adel",
		"said kouachi",
		"saggy tits",
		"Safwat Hijazi",
		"sadomasochistic",
		"sado-masochism",
		"sadomasochism",
		"sadomaso",
		"sado",
		"sadistic",
		"sadist",
		"sadismus",
		"SA80",
		"s&m",
		"run over",
		"roy d mercer",
		"Route 91 Harvest Festival",
		"rotten silver",
		"ropa mascota",
		"Roosh V",
		"Roosh",
		"roll your own",
		"Rolf Harris",
		"roja directa",
		"Rohypnol",
		"rocket strikes",
		"rocket launchers",
		"rocket launcher",
		"Roche",
		"Robert Spencer",
		"Robert Mugabe",
		"robbery",
		"robberies",
		"robber",
		"robbed",
		"road smash",
		"Rizla",
		"rivers of blood",
		"riot",
		"rimjobs",
		"rimjob",
		"rim jobs",
		"rim job",
		"rim",
		"right-wing agitator",
		"right wing",
		"riflescope",
		"rifles",
		"rifle",
		"Ricin",
		"Richard Spencer",
		"rice queen",
		"reza hashemi",
		"revolvers",
		"revolver",
		"Revolutionary Struggle",
		"Revolutionary Party",
		"Revolutionary Organization",
		"Revolutionary Nuclei",
		"Revolutionary Armed Forces",
		"revia",
		"return of kings",
		"Resistance Records",
		"resent fat people",
		"reports of burns",
		"reoffending",
		"renob",
		"Remzi Kartal",
		"remains found",
		"relief operations",
		"release of fumes",
		"rehabilitation",
		"Rehab",
		"regular civil suit",
		"reefer",
		"redtube",
		"redskins",
		"redskin",
		"redneck",
		"red wings",
		"red tube",
		"red light district",
		"Red Hand Defenders",
		"Red Hand Commando",
		"red cross",
		"Red Brigades",
		"recovered a body",
		"recover the bodies",
		"rebels",
		"rebel-held",
		"rebel held",
		"rebel",
		"rear-ended",
		"rear ended",
		"rapist",
		"raping",
		"rapes",
		"raper",
		"raped",
		"rape",
		"raoul weil",
		"Rana Plaza",
		"Rampage",
		"rainbow kiss",
		"raid",
		"raghead",
		"rag week",
		"rag head",
		"Radullan Sahiron",
		"radical",
		"racists",
		"Racist",
		"racism",
		"racially-aggravated",
		"Rache",
		"race-storm",
		"race storms",
		"race storm",
		"race rows",
		"race row",
		"rabbit tests",
		"rabbit testing",
		"rabbit laboratory",
		"rabbit laboratories",
		"rabbit experiment",
		"QZ8501",
		"QZ 8501",
		"quim nuts",
		"quim",
		"queerhole",
		"queerbait",
		"queef",
		"Quds Force",
		"quashie",
		"QC",
		"qat",
		"Qaida",
		"Qaeda",
		"pyongyang",
		"pwt",
		"putos",
		"puto",
		"putas",
		"puta",
		"pussys",
		"pussylicking",
		"pussy",
		"pussies",
		"purple drank",
		"punta",
		"punishment",
		"punching a female",
		"punches were thrown",
		"punched in face",
		"punched female",
		"punch him",
		"punch her",
		"punch employee",
		"punanny",
		"pulseclub",
		"puffmutter",
		"puff",
		"public order offence",
		"pubes",
		"psychoactive substances",
		"psychoactive",
		"psycho",
		"psychedelic",
		"provided arms",
		"provedor",
		"prostitution",
		"prostitutes",
		"Prostitute",
		"prostitutas",
		"prostituierte",
		"prosecution",
		"pro-Russian separatists",
		"pronographie",
		"pro-ISIS",
		"prohibited substance",
		"problem drinking",
		"probe",
		"prison",
		"pricks",
		"prick",
		"price fixing",
		"President Assad",
		"prejudice",
		"preggers",
		"predatordrones",
		"predator drones",
		"Preclampsia",
		"prat",
		"prank call",
		"pr0n",
		"Postpartum",
		"post-mortem",
		"post mortem",
		"positive for meldonium",
		"porstitucion",
		"porntube",
		"pornstars",
		"pornstar",
		"pornsharia",
		"pornotube",
		"pornostar",
		"pornos",
		"pornography",
		"pornofilm",
		"pornodreh",
		"pornodarsteller",
		"pornoclips",
		"porno",
		"pornhub",
		"pornerbros",
		"porn",
		"pormo",
		"pork sword",
		"porchmonkey",
		"porch monkey",
		"poppers",
		"poppen",
		"poor white trash",
		"poopshoot",
		"pooper-scooper",
		"poop",
		"poontang",
		"poonany",
		"poonani",
		"poon tang",
		"poon",
		"poofter",
		"poof",
		"pollock",
		"political unrest",
		"polesmoker",
		"polack",
		"poisonous",
		"poisoning",
		"poison",
		"plunge into canal",
		"plummeting into the",
		"plowed into pedestrians",
		"plowed into a tree",
		"ploughed into traffic",
		"ploughed into market",
		"ploughed into crowds",
		"plochad vosstaniôa",
		"playmates",
		"playboy",
		"play mates",
		"play boy",
		"plata podrida",
		"plane's disappear",
		"planemissing",
		"planedisappeared",
		"planecrash",
		"plane went down",
		"plane was lost",
		"plane was downed",
		"plane narrowly missed",
		"plane lost contact",
		"plane goes down",
		"plane fell",
		"plane evacuated",
		"plane downed",
		"plane disappears",
		"plane disappeared",
		"plane debris",
		"plane came down",
		"plane burst into",
		"plan international",
		"plaids online",
		"Plague",
		"pkk",
		"pistols",
		"pistolet",
		"pistol",
		"pissoff",
		"pissing",
		"pissin",
		"pissflaps",
		"pisses",
		"pissers",
		"pisser",
		"pissed",
		"pisse",
		"piss",
		"pinch one off",
		"pimp",
		"pimmel",
		"pillow biter",
		"pillermann",
		"pillemann",
		"Pill",
		"piefke",
		"physical altercation",
		"phuq",
		"phungky",
		"phuks",
		"phukking",
		"phukked",
		"phuking",
		"phuked",
		"phuk",
		"phonesex",
		"phone scams",
		"phone prank",
		"phone phreaking",
		"phone hacking",
		"Philip Morris",
		"pfeiffe",
		"Peter Chingoka",
		"perverts",
		"perverted",
		"pervert",
		"performance-enhancing",
		"percocet",
		"pepper spray",
		"pep",
		"Peoples Revolutionary Party",
		"Peoples Mujahedin Iran",
		"Peoples Liberation Army",
		"Peoples Congress Ichkeria",
		"Peopledied",
		"peopledead",
		"people trapped",
		"penispuffer",
		"penisfucker",
		"penises",
		"penise",
		"penis",
		"peludo",
		"peludas",
		"películas streaming",
		"películas online gratis",
		"películas streaming",
		"películas online gratis",
		"peliculas online gratis",
		"películas online",
		"pelicula streaming",
		"pegida",
		"peepshows",
		"peepshow",
		"pee-pee",
		"peep shows",
		"pee",
		"Pedophilia",
		"pedophile",
		"pederasty",
		"pederast",
		"PED",
		"peckerwood",
		"peckerhead",
		"pecker wood",
		"pecker tracks",
		"pecker head",
		"pecker cheese",
		"pecker",
		"pearl necklace",
		"PCP",
		"paw patrol",
		"Pavel Skachevsky",
		"Paul Flowers",
		"Patriots of Ukraine",
		"Patriotic Youth League",
		"Patriotic Front",
		"Patlama",
		"passed away",
		"partidos streaming",
		"partidos online",
		"parkland school",
		"Paristerrorattack",
		"parisattacks",
		"parisatrocities",
		"paris mastermind",
		"paris IS",
		"paramilitary",
		"paralyzed",
		"paralysed",
		"panty",
		"panties",
		"panooch",
		"pandora tenerife",
		"pandemic",
		"panamapapers",
		"Pamela Geller",
		"paliza",
		"Palestinian Islamic Jihad",
		"Palestine Liberation Organization",
		"Palestine Liberation Front",
		"Palestine al muslima",
		"pakis",
		"Page 3 pin-up",
		"Page 3 model",
		"paedophilism",
		"paedophilia",
		"paedophiles",
		"paedophile",
		"Paedo",
		"paederast",
		"p0rn",
		"ozone level",
		"ozone layer",
		"OZ162",
		"OxyContin",
		"overweight haters",
		"overturned car",
		"overturned bus",
		"overshoots runway",
		"overheating smartphones",
		"overheating batteries",
		"overdosing",
		"overdose",
		"oven dodger",
		"outbreaks",
		"outbreak",
		"otze",
		"otage",
		"Oso mudslide",
		"Osho Movement",
		"Osbat al Ansar",
		"OsamabinLaden",
		"osama bin laden",
		"Osama",
		"orlandoshooting",
		"orlandogayclub",
		"orlando is burning",
		"orlando club",
		"orgy",
		"orgassmus",
		"orgasmus",
		"orgasms",
		"orgasm",
		"orgasims",
		"orgasim",
		"organspende",
		"Order Solar Temple",
		"Order Flemish Militants",
		"orangemen",
		"Orange Volunteers",
		"orange order",
		"oralsex",
		"opium",
		"opioid",
		"opiate",
		"Opération Chammal",
		"Operation Chammal",
		"on the blob",
		"omarmirseddiquemateen",
		"omarmateen",
		"omar mateen",
		"Omar Ismaïl Mostefai",
		"Omar Ismail Mostefai",
		"omar ismael mostefai",
		"Omar bin Laden",
		"Omar Bakri",
		"Oklahoma tornado",
		"oilspill",
		"oil spill",
		"offshore havens",
		"offshore haven",
		"Official National Front",
		"offensive remarks",
		"offensive lyrics",
		"offensive joke",
		"offensive content",
		"offensive bluster",
		"obscenity",
		"obscene",
		"obituaries",
		"obese",
		"obama muslim",
		"n-words",
		"nutte",
		"nutsack",
		"nut sack",
		"nusra front",
		"nurse",
		"nudity",
		"nudes",
		"nude",
		"nuclear submarine",
		"nuclear strike",
		"nuclear deterrent",
		"nuclear conflict",
		"NSDAPAO",
		"nsdap party",
		"nsdap ao",
		"November 9th Society",
		"notice of violation",
		"nothong",
		"Note 7 fires",
		"Northern League",
		"north korea",
		"nooner",
		"noonan",
		"nookey",
		"Nonce",
		"nombre des morts",
		"no-fly list",
		"no thongs",
		"no panties",
		"no fly zone",
		"no fly list",
		"nipple",
		"nikolas cruz",
		"nikah",
		"nig-nog",
		"nignog",
		"niglet",
		"nightclub santa maria",
		"niggers",
		"nigger",
		"niggaz",
		"niggas",
		"nigga",
		"nigel farage",
		"nig nog",
		"nicotine",
		"NF Flag Group",
		"newpct",
		"New Testament Church",
		"New Peoples Army",
		"New Nationalist Party",
		"New Apostolic Church",
		"New Acropolis",
		"never regained consciousness",
		"nerve gas",
		"neo-nazi",
		"neonazi",
		"neo fascist",
		"Neknomination",
		"Neknominate",
		"necrophilism",
		"necrophilia",
		"NDL",
		"Nazi-themed",
		"Nazism",
		"nazis",
		"naziism",
		"nazi",
		"nawar",
		"naughty rubber duck",
		"naughty",
		"natural england",
		"nationalsozialismus",
		"Nationalsocialistisk Front",
		"Nationalist Front",
		"Nationalist Alliance",
		"National Vanguard",
		"National Socialist Vanguard",
		"National Socialist Society",
		"National Socialist Party",
		"National Socialist Movement",
		"National Socialist Front",
		"National Socialist Action",
		"national socialist",
		"National Socialism Association",
		"national socialism",
		"national rifle association",
		"National Peoples Front",
		"National Party",
		"National Offensive",
		"National Liberation Front",
		"National Liberation Council",
		"National Liberation Army",
		"National Labour Party",
		"National Independence Party",
		"National Federation Total",
		"National Democrats",
		"National Democratic Party",
		"National Democratic Front",
		"National Defence League",
		"National Alliance",
		"national activists",
		"National Action",
		"nathan cirillo",
		"Nasr Javed",
		"nasil buyutulur",
		"narcotics",
		"narcotic",
		"Naqshbandi Order",
		"naltrexone",
		"naked",
		"najim laachraoui",
		"Nairobi Westgate",
		"Nairobi mall",
		"nacktfotos",
		"nacktbilder",
		"nackt",
		"nackidei",
		"Nacionalni stroj",
		"musulman",
		"mustard gas",
		"Mustafa Mohamed Fadhil",
		"muskets",
		"musket",
		"Muscle training",
		"Muscle growth",
		"Muscle gain",
		"murders",
		"murdering",
		"murderers",
		"murderer",
		"murdered",
		"murder",
		"munitions",
		"munition",
		"munging",
		"Mullah Mohammed Omar",
		"Mullah Fazlullah",
		"Mujahidin Indonesia Timur",
		"Mujahideen Forces Caucasus",
		"Mujahideen Forces",
		"mujahideen",
		"mujahed",
		"mugging",
		"mugger",
		"muffin diver",
		"muffdiver",
		"muff licker",
		"muff diver",
		"muff dive",
		"muff",
		"mudslide",
		"ms804",
		"ms 804",
		"mows down",
		"mown down",
		"mowed down crowd",
		"Movement for Oneness",
		"Movement for Jihad",
		"moussa oukabir",
		"Mousa Abu Marzouq",
		"mounted the pavement",
		"mount sinjar",
		"motorwaycrash",
		"motorwayaccident",
		"motorvehiclecollision",
		"motorvehicleaccident",
		"motherfuker",
		"motherfucking",
		"motherfucker",
		"motherfuck",
		"mothafucka",
		"motaba virus",
		"mossack",
		"moskal",
		"Moshe Feiglin",
		"mortos santa maria",
		"morte santa maria",
		"morte kiss",
		"mortar",
		"morphine",
		"morons",
		"moron",
		"moro",
		"morning wood",
		"morning sickness",
		"mooncricket",
		"monkey tests",
		"monkey test",
		"monkey noises",
		"monkey laboratory",
		"monkey laboratories",
		"monkey experiments",
		"monkey experiment",
		"Momodu Bama",
		"Molotov cocktails",
		"molestation",
		"mokhtar belmokhtar",
		"Mohammod Youssuf Abdulazeez",
		"Mohammed Yusuf",
		"mohammed emwazi",
		"Mohammed Atef",
		"Mohammed Ali Hamadei",
		"Mohammed Al Deeni",
		"Mohammed Abdeslam",
		"Mohammad Ali Jafari",
		"Mohamed Lahouaiej-Bouhlel",
		"mohamed lahouaiej bouhlel",
		"mohamed bouhlel",
		"mofo",
		"moda tallas especiales",
		"mocking disability",
		"mobile phone hacking",
		"mobbing",
		"mmwr measles",
		"missing",
		"missiles",
		"missile",
		"missbrauchte kinder",
		"missbrauch von kindern",
		"missbrauch",
		"misogyny",
		"misogynoir",
		"misogynist",
		"misil",
		"Miscarriage",
		"minor burns",
		"minge",
		"miliz",
		"militia",
		"military",
		"militarization",
		"militares egipcios",
		"militants",
		"Militant",
		"milfs",
		"milf",
		"mildronate",
		"mild stroke",
		"Mike Tyson",
		"Mike Guzovsky",
		"Mike Cronk",
		"Mikaeel Kular",
		"migrants perished",
		"migrants drowned",
		"migranten",
		"mierda",
		"mid-air emergencies",
		"mid-air disintegration",
		"mickey mouse",
		"Michael Zehaf-Bibeau",
		"Michael Savage",
		"Michael Brown case",
		"Michael Adebowale",
		"Michael Adebolajo",
		"mice tests",
		"mice testing",
		"mice test",
		"mice laboratory",
		"mice laboratories",
		"mice experiment",
		"MH370",
		"MH17",
		"Methamphetamine",
		"methadone",
		"Mescaline",
		"mers",
		"Merck",
		"meningitis",
		"mejortorrent",
		"mejor torrent",
		"Mein Kampf",
		"meatrack",
		"meat puppet",
		"MDMA",
		"mcfaggot",
		"mcfagget",
		"mayday call",
		"mauritania",
		"Maulana Masood Azhar",
		"mating",
		"mated",
		"mata",
		"masturbation",
		"masturbating",
		"masturbater",
		"masturbate",
		"mastrubation",
		"Massshooting",
		"massacres",
		"massacre",
		"masochismus",
		"Marxist Leninist",
		"martin winterkorn",
		"Marlboro",
		"Mark Bridger",
		"marilou danley",
		"Marijuana",
		"marathonexplosion",
		"marathonbomb",
		"mar Rojo",
		"manslaughter",
		"manning gottlieb",
		"manhunt",
		"Mandaley Casino",
		"Mandaley Bay Hotel",
		"Manchester Arena",
		"manchad",
		"man paste",
		"man haron monis",
		"maltrato",
		"maltratar",
		"malpractice",
		"malnutrition",
		"malaun",
		"malas joyas",
		"makes you stronger",
		"make prank call",
		"Majlis ul Shura",
		"maim",
		"Mahmoud Zahar",
		"Mahmoud Abbas",
		"magic mushrooms",
		"Madeleine McCann",
		"machista",
		"machineguns",
		"machinegun",
		"machetes",
		"machete",
		"macaca",
		"maalbeek metro",
		"lutz bachmann",
		"Lugansk Peoples Republic",
		"Lucky Strike",
		"lucky pierre",
		"luca sirotti",
		"lubra",
		"lube",
		"LSD",
		"Loyalist Volunteer Force",
		"love muscle",
		"love juice",
		"Louis Farrakhan",
		"lostairplane",
		"lost his life",
		"lost his arm",
		"lost her life",
		"lost her arm",
		"lost control",
		"lost airplane",
		"lost a leg",
		"loss of lives",
		"loss of life",
		"losing weight",
		"losing a leg",
		"lorry ploughed into",
		"lorry plough",
		"lord resistance army",
		"lolittas",
		"lolitas",
		"lolita mpegs",
		"lolita",
		"locked in cage",
		"LKW",
		"living environment dictionary",
		"live jasmin",
		"Life threatening",
		"life sentence",
		"lieutenant cullen",
		"Libyan Islamic Fighting",
		"libido",
		"Liberation Tigers Tamil",
		"Liberation of Palestine",
		"lezzie",
		"lewd texts",
		"lewd remark",
		"lewd picture",
		"lewd message",
		"lewd gesture",
		"lethal injection",
		"legal highs",
		"legal actions",
		"legal action",
		"Lee Rigby",
		"lecken",
		"learn quran",
		"League of Empire",
		"Le Petit Cambodge",
		"Le Carillon",
		"lay suit",
		"lawsuits",
		"lawsuit",
		"law suit",
		"lattaque du Bataclan",
		"latest syrian news",
		"Lashkar e Tayyiba",
		"Lashkar e Taiba",
		"Lashkar e Jhangvi",
		"Las Vegas Police",
		"Larnaca",
		"lardass",
		"larceny",
		"lapdance",
		"lap dancing",
		"Landmark Education",
		"Lance Armstrong",
		"Lambert & Butler",
		"lake erie algae",
		"lacerations",
		"laceration",
		"kyoto protocol",
		"kyke",
		"Kurdistan Workers Party",
		"Kurdistan Freedom Falcons",
		"Kurdistan Democratic PartyNorth",
		"Kurdistan Democratic Party",
		"Kurdish Hezbollah",
		"kunt",
		"kums",
		"kum",
		"ku klux klan",
		"krieg",
		"kouachi brothers",
		"kotze",
		"kostenlos download",
		"Kosovar",
		"kootch",
		"kooch",
		"Konzerthalle Bataclan",
		"kondums",
		"kondum",
		"Komplizen",
		"Komalah",
		"Komala",
		"koks",
		"kokain",
		"kock",
		"knocks him unconscious",
		"knocks her unconscious",
		"knockers",
		"Knocked unconscious",
		"knocked him off bike",
		"knocked her off bike",
		"knob",
		"knives and machetes",
		"knife-wielding",
		"knifem",
		"knifed",
		"knife",
		"knarre",
		"Klux Klan",
		"kloake",
		"KKK",
		"kiss",
		"kinky",
		"kinderpornos",
		"kinderpornografie",
		"kinderporno",
		"kinderfilm",
		"kim jong un",
		"kills",
		"killings",
		"killing",
		"killers",
		"killer",
		"killed",
		"kill",
		"kike",
		"kiffen",
		"kids nursery rhymes",
		"kidnaps",
		"kidnapping",
		"kidnappers",
		"kidnapper",
		"kidnapped",
		"kidnap",
		"kick boxing",
		"kick and punch",
		"Khuddam ul Islam",
		"Khmer Rouge",
		"khat",
		"khan rahami",
		"Khalistan Zindabad Force",
		"Khalistan Commando Force",
		"Khalid Sheikh Mohammed",
		"Khalid el-Bakraoui",
		"khalid el bakraoui",
		"khalid and brahim",
		"Khaled Mashal",
		"khaled al rashed",
		"Khaddam ul Islam",
		"Khadafi Abubakar Janjalani",
		"Khadaffy Janjalani",
		"ketamine",
		"Kenya mall",
		"kawum",
		"Kataib Hezbollah",
		"Karipbek Kuyukov",
		"karim cheurfi",
		"kannabis",
		"Kangleipak Communist Party",
		"kanake",
		"Kama Sutra",
		"kalashnikov",
		"Kalaschnikow",
		"kacken",
		"kacke",
		"Kach Kahane Chai",
		"junkies",
		"junglebunny",
		"jungle fever",
		"jungle bunny",
		"Jundallah",
		"Jund al Sham",
		"Jund al Khilafah",
		"Jund al Aqsa",
		"Jumma Kasimov",
		"Julien Blanc",
		"juggs",
		"Joseph Lombardo",
		"joint strike fighter",
		"joint",
		"join IS",
		"Johnson & Johnson",
		"John Russell Houser",
		"John Russel Houser",
		"John Player Special",
		"Joe Pitzel",
		"Joan Guzmán",
		"joan guzman",
		"jizzum",
		"jizz",
		"jizm",
		"jiz",
		"jism",
		"jimmy saville",
		"Jimmy Savile",
		"jijjiboo",
		"Jihadi Wife",
		"Jihadi John",
		"jihad",
		"jiggers",
		"jigger",
		"jiggabo",
		"jigaboo",
		"jets scrambled",
		"jet vanishes",
		"jet came down",
		"Jerry Vlasak",
		"jerk-off",
		"jerk",
		"jenna jameson",
		"Jemaah Islamiyah",
		"jeff dunham",
		"japseye",
		"japie",
		"Japanese Red Army",
		"jap",
		"Jamiat ul Ansar",
		"Jamiat e Islami",
		"James Wright Foley",
		"James Foley",
		"Jamaat Ul Furquan",
		"Jamaat ul Ahrar",
		"Jamaat Mujahideen",
		"Jamaat al Dawa",
		"Jamaah Ansharut Tauhid",
		"Jaish e Mohammed",
		"Jainal Antel Sali",
		"jailbreak phone",
		"jail breaking",
		"jail break phone",
		"jack-off",
		"jackass",
		"jack the ripper",
		"jack off",
		"Jack Buckby",
		"jack and jill",
		"Jacintha Saldanha",
		"jacek międlar",
		"Jaber A. Elbaneh",
		"Istanbulda Teror Saldirisi",
		"istanbul sultanahmet",
		"Israeli-occupied",
		"israeli occupied",
		"Israel-Gaza conflict",
		"Isnilon Totoni Hapilon",
		"Ismael Omar Mostefai",
		"islamic state syria",
		"islamic state iraq",
		"islamic state in",
		"Islamic State group",
		"islamic state",
		"Islamic Raiders Front",
		"Islamic Movement Uzbekistan",
		"Islamic Jihad Union",
		"Islamic Jihad Movement",
		"Islamic Jihad",
		"Islamic fanatics",
		"Islamic Combatant Group",
		"isis",
		"ISIL",
		"isid saldirisi",
		"IS Zynismus",
		"is stronghold",
		"is fighters",
		"is fighter",
		"is armed group",
		"Irish Republican Army",
		"Irish Peoples Liberation",
		"Irish Liberation Army",
		"iraqi freedom",
		"iraq and syria",
		"iphone hack",
		"intoxication",
		"intoxicated",
		"Intihar",
		"Interstate 15",
		"internet trolls",
		"International Third Position",
		"intent to supply",
		"insurgency",
		"insulting language",
		"inquest",
		"inmates",
		"injury",
		"injuring several",
		"injuring dozens",
		"injuries",
		"injurie",
		"injured",
		"injun",
		"injection timing",
		"influenza 1918",
		"inflammatory remarks",
		"Infections",
		"infected with hepatitis",
		"infant mortality",
		"indonesia mujahidin group",
		"Indonesia Mujahideen Group",
		"Indian Mujahideen",
		"indecent images",
		"incy wincy spider",
		"incrediblecrash",
		"incite prejudice",
		"incite hatred",
		"incidents in Berlin",
		"incidents",
		"incident",
		"incest",
		"in flight anomaly",
		"in coma",
		"in a coma",
		"imprisonment",
		"imprisoned",
		"impound",
		"Imad Mughniyah",
		"ill-fated plane",
		"ill-fated aircraft",
		"illegal",
		"ill fated aircraft",
		"ill",
		"ignifugos",
		"ied",
		"identifying the body",
		"Ibrahim Samaha",
		"Ibrahim Salih Mohammed",
		"Ibrahim Mousawi",
		"Ibrahim Hassan al-Asiri",
		"Ibrahim el-Bakraoui",
		"ibrahim el bakraoui",
		"Ibrahim Abdeslam",
		"Ian Watkins",
		"Hyundai Tucson",
		"Hypertension",
		"hustler",
		"huren",
		"hure",
		"hung",
		"humping",
		"hummer",
		"human tests",
		"human test",
		"human shields",
		"human experiments",
		"human experiment",
		"Hukbalahap",
		"Huhanpai",
		"huelgas",
		"huelga",
		"hudna",
		"hucka",
		"Houthis",
		"houses burned",
		"housefire",
		"hotsex",
		"hostage-takers",
		"hostages",
		"hostage",
		"hospitalized",
		"hospitalised",
		"hospitalisation",
		"horsemeat",
		"horse meat",
		"Horrified witnesses",
		"horrendous",
		"horny",
		"horniest",
		"hork",
		"hooker",
		"honky",
		"honkey",
		"homophobics",
		"homophobic",
		"homophobia",
		"homophobe",
		"homodumbshit",
		"homicide",
		"Holy Land Foundation",
		"holocaust",
		"Hofstad Network",
		"hoe",
		"hodgie",
		"hobbyhure",
		"ho",
		"Hizbul Mujahideen",
		"Hizb ut Tahrir",
		"hitler",
		"hit by a train",
		"hit and run",
		"hit a drone",
		"his charred remains",
		"hippy crack",
		"Hilafet Devleti",
		"hijacks",
		"Hijacker",
		"Hijacked",
		"hijack",
		"high speed pursuit",
		"hgv overturned",
		"Hezbollah Al Hejaz",
		"hershey highway",
		"herpes",
		"Heroines",
		"Heroin",
		"Heritage Front",
		"her charred remains",
		"hentai",
		"Henchmen",
		"helicopter missing",
		"held for ransom",
		"held by is",
		"heist",
		"heiﬂe girls",
		"heavy shelling",
		"heather heyer",
		"Heathen Front",
		"Heart rate monitor",
		"health benefits",
		"head-on smash",
		"headless body",
		"head wound",
		"Head trauma",
		"head shop",
		"hcov",
		"havoc",
		"hating",
		"hatespeech",
		"hates peech",
		"hateful rhetoric",
		"hateful messages",
		"hateful comments",
		"hated",
		"hatecrimes",
		"hate",
		"Hassan Nasrallah",
		"hash",
		"Hasdied",
		"Hasan Mahsum",
		"Harkat ul Mujahideen",
		"Harkat Jihad alIslami",
		"hard-on",
		"hardcoresex",
		"hardcore",
		"hard on",
		"hard core",
		"harassing text",
		"harassement",
		"harass",
		"Harakat Ul MujahideenAlami",
		"Haqqani network",
		"hangover",
		"hanged himself",
		"handjob",
		"handguns",
		"handgun",
		"hand job",
		"hammer-wielding",
		"Hammerskins",
		"hammered",
		"Hamas",
		"hallucinogenic",
		"halfbreed",
		"Hakimullah Mehsud",
		"Haiyan",
		"Hagupit",
		"Hafiz Saeed",
		"Hafiz Muhammad Saeed",
		"Hackingdeath",
		"hacking",
		"hackers",
		"hacker",
		"Hackedtodeath",
		"hacked",
		"hack phone",
		"hack",
		"GWI9525",
		"gunshots",
		"gunshot",
		"guns",
		"gunpowder",
		"gunpoint",
		"gunned down",
		"gunmen",
		"gunman",
		"gunfire",
		"guncrime",
		"gun shot wounds",
		"gun fire",
		"gun",
		"Guilty",
		"guido",
		"guerrilla",
		"guerra",
		"guarros",
		"guarro",
		"guarras",
		"guarra",
		"groupsex",
		"Groupe Etat islamique",
		"grostulation",
		"groid",
		"gringos",
		"gringo",
		"grievous bodily harm",
		"grenfell tower",
		"grenande",
		"grenade",
		"Greater Britain Movement",
		"graphic content",
		"Grace Mugabe",
		"gore",
		"gorditas sin",
		"gordita sin",
		"goombah",
		"gooky",
		"gookeye",
		"gook",
		"good prank calls",
		"gooch",
		"gollywog",
		"golliwog",
		"goldman sachs",
		"goldman sach",
		"golden shower",
		"Golden Dawn",
		"goebbels",
		"goddamnit",
		"goddamn",
		"god damn it",
		"god damn",
		"gob the knob",
		"go down on",
		"gm vegitables",
		"gm vegetables",
		"gm veg",
		"gm products",
		"gm meat",
		"gm crops",
		"glory hole",
		"glock",
		"global pandemic",
		"global outbreak",
		"global measles outbreak",
		"girls without",
		"girl in panty",
		"girl in mini",
		"gilf",
		"Gideon Gono",
		"GHB",
		"get laid",
		"get it up",
		"get it on",
		"get bent",
		"German Alternative",
		"genocide",
		"genital",
		"genetically modified vegitables",
		"genetically modified veg",
		"genetically modified meat",
		"genetically modified food",
		"genetically modified crops",
		"genetically modified",
		"gendarmerie",
		"gedankengut",
		"GBH",
		"Gaza tunnels",
		"Gaza refugees",
		"gaza hamas",
		"Gaza conflict",
		"Gaza camp",
		"gaynightclubshooting",
		"Gauloises",
		"gash in his",
		"gash in her",
		"gascylinders",
		"gas leak",
		"gas cylinders",
		"Gary Yourofsky",
		"Gareth Huntley",
		"ganja",
		"Gangster",
		"gangbang",
		"gang member",
		"gang bangs",
		"gang banged",
		"gang bang",
		"gamez",
		"gamergate",
		"game reserve",
		"gambling",
		"Gain muscle",
		"gaggersa",
		"fuuck",
		"fusillade",
		"funny prank calls",
		"funny prank call",
		"fundas movil",
		"fukyou",
		"fuks",
		"fukme",
		"fukinbitch",
		"fukin bitch",
		"fuk",
		"fugly",
		"fuel pressure",
		"fudgepacker",
		"fudge packer",
		"fuckyou",
		"fuckwitt",
		"fuckwit",
		"fuckwad",
		"fuckup",
		"fucktard",
		"fuckstick",
		"fucks",
		"fuckoff",
		"fucknutt",
		"fucknut",
		"fuckme",
		"fuckist",
		"fuckings",
		"fuckingbitch",
		"fucking",
		"fuckinbitch",
		"fuckin",
		"fuckhole",
		"fuckhead",
		"fuckface",
		"fuckersucker",
		"fuckers",
		"fucker",
		"fucked",
		"fuckbutt",
		"fuckbrain",
		"fuckboy",
		"fuckbag",
		"fuckass",
		"fuck",
		"fucck",
		"french kiss",
		"french authorities",
		"freesex",
		"freebasing",
		"freebase",
		"free syrian army",
		"free syria news",
		"free stricken",
		"free spoof call",
		"free spoof",
		"free prank calls",
		"free prank call",
		"free pix",
		"free online phone",
		"free movies",
		"free download",
		"fraud",
		"france mourns",
		"Fox News",
		"foursome",
		"found the bodies",
		"found ablaze",
		"foul-mouthed tirade",
		"foul mouthed",
		"foued mohamed aggad",
		"fotze",
		"format18",
		"Format 18",
		"Forgery",
		"foreign military",
		"Force 17",
		"footfetish",
		"floridanightclub",
		"flood water",
		"flightgoesmissing",
		"flight QZ8501",
		"Flight MS181",
		"flight missing",
		"flight MH370",
		"flight horror",
		"flight goes missing",
		"Flight 9525",
		"flight 93",
		"Flight 9268",
		"Flight 8501",
		"flight 804",
		"Flight 370",
		"flight 17",
		"flash your gash",
		"flamethrower",
		"flamer",
		"flame thrower",
		"flakka",
		"Flag Group",
		"fkk",
		"Fitness videos",
		"Fitness tracker",
		"Fitness First",
		"Fitness DVDs",
		"fisting",
		"fistfucks",
		"fistfuck",
		"firing squad",
		"fires",
		"fire-prone",
		"firefight",
		"firebombed",
		"fireball",
		"Firearms",
		"firearm",
		"fire",
		"fingerfuck",
		"filter tip",
		"fights",
		"fighting",
		"fighter plane",
		"fighter jets",
		"fighter jet",
		"fighter aircraft",
		"Fianna Éireann",
		"fianna eireann",
		"fetish",
		"festa santa maria",
		"ferry sinks",
		"Ferguson unrest",
		"Ferguson officer",
		"femdom",
		"feltch",
		"Felony",
		"felonies",
		"fellatio",
		"felch",
		"felatio",
		"fecv symptoms",
		"Fazul Abdullah Mohammed",
		"faty without",
		"fat-shaming",
		"fatass",
		"fatality",
		"fatalities",
		"fatal",
		"fat without",
		"fat shaming",
		"Fat loss",
		"fascism",
		"farty",
		"farts",
		"fartings",
		"farting",
		"farted",
		"fart",
		"far-right protest",
		"far-right groups",
		"Fariq Hamid",
		"Far Right",
		"fanny",
		"fanaticism",
		"famine",
		"falsifying",
		"fallen sick",
		"fall overboard",
		"fake caller id",
		"Fahd al Quso",
		"fagtard",
		"fags",
		"fagots",
		"fagot",
		"faggs",
		"faggotcock",
		"faggot",
		"faggit",
		"fagging",
		"fagfucker",
		"fagbag",
		"fag",
		"facist",
		"face sitting",
		"fabien clain",
		"eyetie",
		"Extremists",
		"extremist",
		"extremism",
		"extreme religious groups",
		"Extortion",
		"extermination camps",
		"extermination",
		"Extensive burns",
		"extasy",
		"explosives",
		"explosive",
		"explosions",
		"explosion",
		"exploitation",
		"explodes",
		"explode",
		"explicit text message",
		"explicit photo",
		"expletives",
		"exhaust gas recirculation",
		"executions",
		"executioner",
		"execution",
		"evil",
		"evd 27 ebola",
		"evacuation",
		"evacuated",
		"evacuate",
		"euthanising",
		"euthanasia",
		"euphrates shield",
		"Ethniko Laiko Metopo",
		"ethnic cleansing",
		"escortservice",
		"escorts",
		"escort",
		"escalating conflict",
		"erotica",
		"erotic",
		"ermordet",
		"Erich Gliebe",
		"Eric Garner",
		"Ergenekon",
		"erection",
		"environ online",
		"enslavement",
		"enslaved",
		"English National Association",
		"English Defence League",
		"England First Party",
		"engine malfunction",
		"engine failure",
		"enduring freedom",
		"endangered",
		"emergency",
		"embezzling",
		"embezzlement",
		"embezzled",
		"embezzle",
		"Elliot Rodger",
		"elitetorrent",
		"elitefreak",
		"electronics exploding",
		"electronic threat",
		"electrocution",
		"el-Bakraoui brothers",
		"el bakraoui brothers",
		"ejaculation",
		"ejaculatings",
		"ejaculating",
		"ejaculates",
		"ejaculated",
		"ejaculate",
		"Egyptian Islamic Jihad",
		"Edward Snowden",
		"EDL",
		"ecstasy tablets",
		"Ecstacy",
		"e-cigarette",
		"e-cig",
		"Ebola",
		"earthquakes",
		"e coli",
		"Dzhokhar Tsarnaev",
		"dynamite",
		"dyke",
		"dwi",
		"durchfall",
		"dumshit",
		"dumbshit",
		"dumbfuck",
		"dumbass",
		"dumass",
		"Dukhtaran e Millat",
		"dui",
		"duane dog chapman",
		"Duane 'Dog' Chapman",
		"du Bataclan",
		"drunkdriving",
		"drunk",
		"Drummer Lee Rigby",
		"drugs",
		"drugged",
		"drug",
		"drown",
		"drone strikes",
		"driver slammed into",
		"driver lost control",
		"driver jailed",
		"drinking problem",
		"drink problem",
		"drink driving",
		"drink driver",
		"draize tests",
		"draize testing",
		"draize test",
		"drags girl",
		"drags boy",
		"dragged into water",
		"downing the aircraft",
		"downed plane",
		"down the plane",
		"douchewaffle",
		"douchebag",
		"douche",
		"double penetration",
		"dothead",
		"Doping",
		"dopers",
		"doped",
		"Dope",
		"dookie",
		"doo-doo",
		"doochbag",
		"dong",
		"Donetsk Peoples Republic",
		"donald trump",
		"doktorspiele",
		"Dogging",
		"doggie style",
		"Doggie",
		"dog tests",
		"dog testing",
		"dog test",
		"dog laboratory",
		"dog laboratories",
		"dog experiment",
		"Divine Light Mission",
		"distracted driver",
		"dissident republican",
		"disparos",
		"dislocation",
		"disgusting tweets",
		"disfiguring burns",
		"diseases",
		"diseased",
		"disease",
		"discovered the bodies",
		"disasters",
		"disaster",
		"dipsomania",
		"dipshit",
		"dink",
		"dingle berry",
		"dildos",
		"dildo",
		"dike",
		"Difang Jiaohui",
		"Dieudonné Mbala Mbala",
		"dieudonne mbala mbala",
		"dieselgate",
		"dies",
		"dieing",
		"died",
		"die",
		"dickwod",
		"dickweed",
		"dickweasel",
		"dickwad",
		"dicksucker",
		"dickslap",
		"dicks",
		"dickmonger",
		"dickmilk",
		"dickjuice",
		"dickhole",
		"dickhead",
		"dickfucker",
		"dickfuck",
		"dickface",
		"dickbeaters",
		"dickbag",
		"dick",
		"Dianova",
		"detox",
		"detonate",
		"detained",
		"destroyed homes",
		"Desert Eagle",
		"derogatory",
		"derailed",
		"depression",
		"demerol",
		"degradation of women",
		"deggo",
		"deformity",
		"deforestation",
		"defloration",
		"defilement",
		"defile",
		"defeat devices",
		"defeat device",
		"deepthroat",
		"deep throat",
		"Deendar Anjuman",
		"decomposing bodies",
		"deception",
		"Decapitation",
		"decapitated",
		"Decapitate",
		"deathtoll",
		"deaths",
		"death",
		"dealer",
		"deadly",
		"dead",
		"dazed and bloodied",
		"days of clashes",
		"Dayar Mongol",
		"dago",
		"Daesh",
		"cyberfucked",
		"cyberfuck",
		"cyberfuc",
		"cyberbullying",
		"cyberattack",
		"cuntslut",
		"cunts",
		"cuntrag",
		"cuntlicker",
		"cunthole",
		"cuntface",
		"cunt",
		"cunnilingus",
		"cunnie",
		"cunillingus",
		"cunilingus",
		"cumtart",
		"cumswallow",
		"cumslut",
		"cumshots",
		"cumshot",
		"cums",
		"cumming",
		"cummer",
		"cumjockey",
		"cumguzzler",
		"cumfiesta",
		"cumeating",
		"cumdumpster",
		"cumbubble",
		"Cumann na mBan",
		"cum",
		"culture of fear",
		"cucumber salmonella",
		"Crystal Methodist",
		"crystal meth",
		"crybaby freak daddy",
		"crushed by falling",
		"crusades",
		"crusade",
		"crotch jockey",
		"Critically wounded",
		"Critically injured",
		"critically ill",
		"critical injuries",
		"critical conditions",
		"critical condition",
		"critical but stable",
		"crisises",
		"crisis",
		"criminals",
		"criminal",
		"crimes",
		"crime",
		"credible threat",
		"credible new threats",
		"crashing",
		"crashes",
		"crashed",
		"crash",
		"crapper",
		"crap",
		"crank phone calls",
		"crank calls",
		"crank call",
		"Craig Stephen Hicks",
		"crackcocaine",
		"crack pipe",
		"covered in flames",
		"court order",
		"court of appeal",
		"court case",
		"counsel law",
		"cougar 13",
		"cotdeath",
		"Costa Concordia",
		"corruption",
		"corrupt",
		"cooter",
		"coonass",
		"coon",
		"coochy",
		"coochie",
		"contempt of court",
		"contamination",
		"contact was lost",
		"Constitutional Movement",
		"coños",
		"coño",
		"conflict in syria",
		"condoms",
		"condom",
		"Conception",
		"comshots",
		"communists",
		"communist",
		"communism",
		"come stain",
		"combing the area",
		"combat forces",
		"Combat 18",
		"com shots",
		"Column 88",
		"columbine",
		"collusions",
		"collusion",
		"collude",
		"collisions",
		"collision",
		"collapsed building",
		"codeine",
		"cocksucks",
		"cocksucking video",
		"cocksucker",
		"cocksucked",
		"cocksmoker",
		"cocksmith",
		"cockshit",
		"cocks",
		"cockpit",
		"cocknugget",
		"cocknose",
		"cockmuncher",
		"cockmonkey",
		"cockmongruel",
		"cockmongler",
		"cockmaster",
		"cockknoker",
		"cockjockey",
		"cockhead",
		"cockfucker",
		"cockface",
		"cockcontrol",
		"cockburger",
		"cockbite",
		"cockass",
		"cock",
		"Cocaine",
		"clusterfuck",
		"clitoris",
		"clitfuck",
		"clitface",
		"clit",
		"class suits",
		"class suit",
		"class actions",
		"class action",
		"Clanging of Swords",
		"civil suit",
		"civil disorder",
		"circle jerk",
		"cigs",
		"cigarillo",
		"cigarette",
		"cigar",
		"ciapak",
		"churka",
		"chunger",
		"chugs",
		"chugging",
		"chug",
		"chubby chaser",
		"cholo",
		"chode",
		"chochos",
		"chocho",
		"choad",
		"children of god",
		"childhoodobesity",
		"childhood obesity",
		"child soldiers",
		"child combatants",
		"cherif kouachi",
		"cherif and said",
		"chemical spill",
		"chemical leaks",
		"chemical leak",
		"chemical incident",
		"chemical dependency",
		"Cheeki Rafiki",
		"Chastity",
		"charlie hebdo office",
		"CellCase",
		"celebrity prank calls",
		"ceiling collapsed",
		"cease-fire",
		"ceasefire",
		"Cazeneuve",
		"caused burns",
		"Caucasus Emirate",
		"cathouse",
		"catastrophy",
		"catastrophic",
		"catalytic reduction",
		"Catalan separatists",
		"Casualties",
		"castro",
		"casaulties",
		"cartel",
		"Cars collided",
		"carrier fleet",
		"carpetmuncher",
		"carpet muncher",
		"carpet burning",
		"carnage in Paris",
		"carnage",
		"carlos ghosn",
		"Carinthian Homeland Service",
		"Carecas do ABC",
		"carcrash",
		"carcinogenic",
		"carcinogen",
		"carbine",
		"car struck",
		"car strikes",
		"car smash",
		"car plunged off",
		"car plummeted",
		"car ploughs",
		"car ploughed",
		"car plough",
		"car hitting people",
		"car hit them",
		"car flipped",
		"car crash",
		"Car collided",
		"car chase",
		"capsize",
		"cannon",
		"cannabis",
		"Canlibomba",
		"Canli Bomba",
		"cancer",
		"Campral",
		"cameltoes",
		"cameltoe",
		"camel jockey",
		"cam4",
		"california air resources",
		"cache of arms",
		"butts",
		"buttplug",
		"butthole",
		"buttfucker",
		"buttfucka",
		"buttfuck",
		"butt",
		"butchery",
		"Bushmaster",
		"bush boogie",
		"bus smash",
		"bus flipped",
		"bus falls off",
		"bursts its banks",
		"burst into flames",
		"burrhead",
		"burnt interior",
		"burnt alive",
		"burns to his",
		"burns to her",
		"burns on his",
		"burns on her",
		"burning vehicle",
		"burning to the ground",
		"burning neighborhood",
		"burning ferry",
		"burning car",
		"burned down",
		"burned beyond recognition",
		"Burned alive",
		"Buried under rubble",
		"buried alongside",
		"burglary",
		"Burglars",
		"bung hole",
		"bumblefuck",
		"bum-bandit",
		"bum bandit",
		"bullying",
		"bully",
		"bullied",
		"bullets",
		"bullet",
		"bulimia",
		"bukkake",
		"BUK",
		"buildings to collapse",
		"building set alight",
		"Building collapse",
		"buggery",
		"bugger",
		"buggary",
		"buggar",
		"buckshot",
		"bucket head",
		"Bryce Williams",
		"brutal",
		"Brussels Bombers",
		"bruising",
		"brotherfucker",
		"broken wrist",
		"broken leg",
		"broken bone",
		"broken back",
		"broke his back",
		"broke her back",
		"British Peoples Party",
		"British National Party",
		"British National Front",
		"British League Servicemen",
		"British First Party",
		"British Empire Party",
		"British Democratic Party",
		"Bristol-Myers Squibb",
		"Bristol Myers Squibb",
		"bridge jump",
		"bridge collapse",
		"breathalyzer",
		"breathalyser",
		"breaks his back",
		"breaks her back",
		"brawl",
		"Branch Davidians",
		"brain damage",
		"Brahim el-Bakraoui",
		"brahim el bakraoui",
		"Brahim Abdeslam",
		"boy band",
		"Boulevard Voltaire",
		"Boston Marathon bombers",
		"Boston Church Christ",
		"bordell",
		"booze",
		"bootylicious",
		"booty",
		"bootie",
		"bootee",
		"boong",
		"booby-trapped vehicle",
		"booby trapped vehicle",
		"boobs",
		"boobies",
		"boob",
		"boning",
		"bongobongoland",
		"bongo bongo land",
		"bong",
		"boners",
		"boner",
		"bondage",
		"boming",
		"bombshell",
		"bombs",
		"bomb-making",
		"bombmaker",
		"bomblets",
		"bombings",
		"bombing",
		"Bomber",
		"Bomben",
		"Bombe",
		"bombas",
		"bombardeo",
		"bombardements",
		"Bombali Saldiri",
		"Bomba",
		"bomb",
		"bollox",
		"bollocks",
		"bollock",
		"bokoharam",
		"boko haram",
		"boink",
		"bohunk",
		"body was dumped",
		"body was discovered",
		"body was burned",
		"body of a woman",
		"body of a man",
		"Body mass index",
		"body found",
		"Body changes",
		"body armour",
		"body armor",
		"bodies were found",
		"bodies were discovered",
		"Bodem",
		"boats in distress",
		"blut",
		"blumovie",
		"bluemuvie",
		"bluemovie",
		"bluemove",
		"bluemouvie",
		"bluegum",
		"blue movie",
		"blows",
		"blown himself up",
		"blowjobs",
		"blowjob",
		"blowing themselves up",
		"blowie",
		"blow",
		"bloody",
		"bloodshed",
		"blood-covered",
		"bloodbath",
		"blood",
		"Bloed",
		"blew themselves up",
		"blew himself up",
		"blew herself up",
		"bleeding",
		"bleed",
		"blasts",
		"blaster",
		"blasted",
		"blast",
		"blasen",
		"blackmail",
		"bityouth",
		"bitchy",
		"bitchtits",
		"bitching",
		"bitchin",
		"bitches",
		"bitchers",
		"bitcher",
		"bitchass",
		"bitch",
		"birth defect",
		"bioterrorism",
		"Binge Drinking",
		"Bin Laden",
		"billowing flames",
		"bilalhadfi",
		"Bilal Hadfi",
		"bigots",
		"bigotry",
		"bigot",
		"biatch",
		"betting",
		"bestiality",
		"bestial",
		"best prank calls",
		"Bernard Cazeneuve",
		"Beretta",
		"berates overweight people",
		"bell end",
		"behind bars",
		"beheads",
		"beheading",
		"beheaded",
		"behead",
		"began sinking",
		"beef curtains",
		"beat your meat",
		"beat off",
		"beastility",
		"beastiality",
		"beastial",
		"beaner",
		"bdsm",
		"bayonet",
		"battling the flames",
		"battlefield",
		"Bataclan concert hall",
		"Bataclan",
		"bastard",
		"Bashar al-Assad",
		"Bashar al Assad",
		"baring her breasts",
		"bare breasted",
		"barbiturates",
		"barbaric",
		"banned substance",
		"banned diesels",
		"bampot",
		"Balochistan Liberation Army",
		"ball sack",
		"ball of flame",
		"ball licking",
		"ball licker",
		"badly hurt",
		"badly burned",
		"badger cull",
		"babes",
		"Babbar Khalsa International",
		"Ayman al Zawahiri",
		"ayasofya meydani",
		"Awlaki",
		"auschwitz",
		"Aum Shinrikyo",
		"attentat",
		"attacks",
		"attackers",
		"attacker",
		"attack",
		"atrocity",
		"atrocities",
		"asylanten pack",
		"asylanten",
		"asyl bewerber",
		"asyl",
		"asswipe",
		"asswad",
		"asssucker",
		"assshole",
		"assshit",
		"asspirate",
		"assnigger",
		"assmuncher",
		"assmunch",
		"assmonkey",
		"asslicker",
		"asslick",
		"assjacker",
		"asshopper",
		"asshole",
		"asshead",
		"asshat",
		"assgoblin",
		"assfucker",
		"assfuck",
		"assface",
		"asses",
		"asscracker",
		"asscock",
		"assclown",
		"assbite",
		"assbanger",
		"assbandit",
		"assbag",
		"assault",
		"Assata Shakur",
		"assassination",
		"assassinated",
		"assassinate",
		"assad",
		"ass2mouth",
		"ass",
		"ash dieback",
		"Asbo",
		"Aryan Nations",
		"Aryan Guard",
		"Aryan Brotherhood",
		"Artur Ryno",
		"artillery",
		"arsonists",
		"arsonist",
		"arson",
		"arsewipe",
		"arsewad",
		"arseshole",
		"arseshit",
		"arses",
		"arsepirate",
		"arsemonkey",
		"arselick",
		"arsejacker",
		"arsehopper",
		"arsehole",
		"arsehead",
		"arsehat",
		"arsefuck",
		"arse2mouth",
		"arse2 mouth",
		"arse",
		"arrests",
		"arrested",
		"arrest",
		"Army of Islam",
		"armut",
		"armoured vehicle",
		"armee",
		"armament",
		"aqim",
		"AQAP",
		"April Jones",
		"Anwar al-Awlaki",
		"Anwar al Awlaki",
		"anus",
		"anti-doping",
		"anti-Assad",
		"anti white",
		"anti social behaviour",
		"anti assad",
		"anthrax",
		"Ansaru",
		"Ansar Dine",
		"Ansar al-Sharia",
		"Ansar al Sharia",
		"Ansar al Islam",
		"anorexic",
		"anorexia",
		"annexing",
		"annexation of Crimea",
		"annexation",
		"annabelle freaks out",
		"Ann Maguire",
		"Anjem Choudary",
		"anita sarkeesian",
		"anisamri",
		"anis amri",
		"animalsex",
		"animalabuse",
		"animal tests",
		"Animal Testing",
		"animal tester",
		"animal test",
		"animal suffer",
		"animal rhymes",
		"animal product",
		"animal experiment",
		"animal cruelty",
		"animal cosmetics",
		"angeldust",
		"angel dust",
		"Andreas Lubitz",
		"Andreas Guenter Lubitz",
		"anders breivik",
		"Anas al Liby",
		"anarchists",
		"anarchist",
		"analsex",
		"analingus",
		"analcoholic",
		"analcam",
		"anal",
		"ampland",
		"Amphetamine",
		"amp land",
		"ammunition",
		"ammo",
		"Amir Siddique",
		"amedy coulibaly",
		"Alt Right",
		"alt left",
		"Al-Shabaab",
		"alquilo",
		"alquilar",
		"al-Qa'ida",
		"al-Qaida",
		"alQaida",
		"AlQaeda",
		"Alphabet",
		"allegations",
		"allegation",
		"Allahu Akbar",
		"All Tripura Tiger",
		"alkyl",
		"Alison Parker",
		"Alibi",
		"Ali Atwa",
		"Ali Abu Mukhammad",
		"aleppo syria news",
		"alek minassian",
		"alcoholism",
		"alcoholic",
		"al-Baghdadi",
		"Al Umar Mujahideen",
		"al Shabab",
		"Al Shabaan",
		"al Shabaab",
		"Al Quds Army",
		"al Qa'ida",
		"al Qaida",
		"al Qaeda",
		"al nusra front",
		"Al Nusra",
		"Al Mourabitoun",
		"al harb",
		"al Haramain Foundation",
		"Al Ghurabaa",
		"al Furqan",
		"al Baghdadi",
		"Al Badr",
		"al assad syria",
		"al Aqsa Foundation",
		"al Anbar",
		"AK47",
		"ak 47",
		"Ajnad Misr",
		"airstrikes",
		"airstrike",
		"airplanemissing",
		"airgun",
		"Airdisaster",
		"Aircrash",
		"aircraft went down",
		"aircraft disappeared",
		"Airaccident",
		"air strike",
		"ahole",
		"Ahmed Mohammed Hamed",
		"Ahmed Godane",
		"Ahmed Ghailani",
		"Ahmed Almuhamed",
		"ahmed abdi godane",
		"Ahmad Rahami",
		"Ahmad Khan Rahami",
		"Ahmad Al Mohammad",
		"agony",
		"Affray",
		"adulttoon",
		"adultstore",
		"adultcheck",
		"adolf hitler",
		"Aden Hashi Farah",
		"adel kermiche",
		"addictive",
		"addiction",
		"addicted",
		"addict",
		"Adam Yahiye Gadahn",
		"Adam Ward",
		"actual bodily harm",
		"acts of intolerance",
		"Action Front",
		"acidattack",
		"accidents",
		"accident",
		"acamprosate",
		"abusive",
		"abused",
		"abuse",
		"Abubakar Shekau",
		"Abu Usman Adil",
		"Abu Sayyaf",
		"Abu Nidal Organization",
		"Abu Muhammad Jawlani",
		"Abu Bakr al-Baghdadi",
		"abu bakr al baghdadi",
		"Abu Bakar Bashir",
		"abortion",
		"ABH",
		"Abdurajik Abubakar Janjalani",
		"Abdullah Yusuf Azzam",
		"Abdullah Sungkar",
		"Abdullah Mansour",
		"Abdullah Azzam Brigades",
		"Abdullah Ahmed Abdullah",
		"Abdul Shakoor Turkistani",
		"Abdul Rahman Yasin",
		"Abdul Ha",
		"Abdul Alim Musa",
		"abduction",
		"Abdeslam",
		"Abdel-Hamid Abu Oud",
		"Abdelhamid Abaaoud",
		"abdel malik petitjean",
		"Abbdulakbak",
		"Abatcha Flatari",
		"69sex",
		"3d sexvilla",
		"911",
		"anti islam",
		"anti islamic",
		"anti lgbt",
		"anti Muslim",
		"anti semites",
		"anti semitic",
		"antisemitic",
		"nationalist",
		"rightwing",
		"Russian National Unity",
		"russian separatists",
		"russian trolls",
		"islamic extremists",
		"jihadist",
		"jihadists",
		"jihadiwife",
		"Taliban",
		"extremiste",
		"armed conflict",
		"armed groups",
		"Syria conflict",
		"Syria rebels",
		"Syrian conflict",
		"Syrian opposition",
		"Syrian troops",
		"qaran",
		"quraan",
		"quran",
		"quran audio",
		"quran english",
		"quran in english",
		"quran mp3",
		"quran online",
		"quran reading",
		"quran recitation",
		"quran translation",
		"Socialist",
		"Sunni Islam",
		"sunni scholars",
		"quranists",
		"al islam",
		"alquran",
		"asian flu ",
		"Syrian pro-government",

	];